Update requirements.txt
eval.py requires the latest version of imgaug, which is 0.4.0. Without it, you get this error message:
ImportError: cannot import name 'SegmentationMapsOnImage' from 'imgaug.augmentables.segmaps' (/usr/local/lib/python3.7/dist-packages/imgaug/augmentables/segmaps.py)